/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import modelo.Conexion;
import modelo.EmpleadoVO;

/**
 *
 * @author jhond
 */
public class vistaClientes extends javax.swing.JFrame {

    private EmpleadoVO user;

    /**
     * Creates new form vistaEmpleados
     */
    public vistaClientes(EmpleadoVO user) {
        this.user=user;
        initComponents();
        this.setLocationRelativeTo(null);
        this.btnEliminar.setVisible(false);
        this.btnEliminar1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblci = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lblapellido = new javax.swing.JLabel();
        lbltelefono = new javax.swing.JLabel();
        lbldireccion = new javax.swing.JLabel();
        lblcorreo = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoPequeño.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");

        lblci.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblci.setText("CI");

        lblnombre.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblnombre.setText("Nombre");

        lblapellido.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblapellido.setText("Apellido");

        lbltelefono.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbltelefono.setText("Telefono");

        lbldireccion.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lbldireccion.setText("Dirección");

        lblcorreo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblcorreo.setText("Correo electronico");

        txtCedula.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaActionPerformed(evt);
            }
        });
        txtCedula.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCedulaFocusLost(evt);
            }
        });
        txtCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCedulaKeyTyped(evt);
            }
        });

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        txtApellido.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApellidoFocusLost(evt);
            }
        });
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });

        txtTelefono.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        txtTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelefonoFocusLost(evt);
            }
        });
        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        txtDireccion.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDireccionFocusLost(evt);
            }
        });

        txtCorreo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtCorreo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoFocusLost(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/añadir.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.png"))); // NOI18N
        btnEliminar1.setText("Modificar");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/home.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblnombre)
                            .addComponent(lbldireccion)
                            .addComponent(lblcorreo)
                            .addComponent(lblci)
                            .addComponent(lblapellido)
                            .addComponent(lbltelefono))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDireccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnHome)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblci))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblnombre))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblapellido))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbltelefono))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbldireccion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblcorreo)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregar)
                        .addGap(4, 4, 4)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        vistaMenuPrincipal vista = new vistaMenuPrincipal(user); 
        vista.setVisible (true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void txtCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCedulaKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if ((int)validar>32 && (int)validar<=47
                || (int)validar>58 && (int)validar<=255) {
            getToolkit().beep();
            evt.consume();
        }
        if (txtCedula.getText().length()>9) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtCedulaKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            evt.consume();
        }
        if (Character.isSpace(validar)) {
            getToolkit().beep();
            evt.consume();
        }
        if ((int)validar>32 && (int)validar<=47
                || (int)validar>58 && (int)validar<=64
                || (int)validar>91 && (int)validar<=96
                || (int)validar>123 && (int)validar<=255) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            evt.consume();
        }
        if (Character.isSpace(validar)) {
            getToolkit().beep();
            evt.consume();
        }
        if ((int)validar>32 && (int)validar<=47
                || (int)validar>58 && (int)validar<=64
                || (int)validar>91 && (int)validar<=96
                || (int)validar>123 && (int)validar<=255) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if ((int)validar>32 && (int)validar<=47
                || (int)validar>58 && (int)validar<=255) {
            getToolkit().beep();
            evt.consume();
        }
        if (txtTelefono.getText().length()>9) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtCorreoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoFocusLost
        // TODO add your handling code here:
         Pattern pat = null;
        Matcher mat = null;
        pat = Pattern.compile("^[\\w\\-\\_\\+]+(\\.[\\w\\-\\_]+)*@([A-Za-z0-9-]+\\.)+[A-Za-z]{2,4}$");
        mat = pat.matcher(txtCorreo.getText());
        if (mat.find()) {
            lblcorreo.setForeground(Color.green);
        } else {
            //JOptionPane.showMessageDialog(null, "Correo electrónico incorrecto","Validar correo electrónico",JOptionPane.INFORMATION_MESSAGE);
            lblcorreo.setForeground(Color.red);
        }
    }//GEN-LAST:event_txtCorreoFocusLost

    private void txtCedulaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCedulaFocusLost
        // TODO add your handling code here:
         if ("".equals(txtCedula.getText())) {
            //JOptionPane.showMessageDialog(null, "Cédula de identidad incorrecta","Validar cédula de identidad",JOptionPane.INFORMATION_MESSAGE);
            lblci.setForeground(Color.red);
        } else {
            if (!validaCedula(txtCedula.getText())) {
                //JOptionPane.showMessageDialog(null, "Cédula de identidad incorrecta","Validar cédula de identidad",JOptionPane.INFORMATION_MESSAGE);
                lblci.setForeground(Color.red);
            }else{
                lblci.setForeground(Color.green);
            }
        }
    }//GEN-LAST:event_txtCedulaFocusLost

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        // TODO add your handling code here:
        if (txtNombre.getText().length()<2) {
            lblnombre.setForeground(Color.red);
        }else{
            lblnombre.setForeground(Color.green);
        }
    }//GEN-LAST:event_txtNombreFocusLost

    private void txtCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellidoFocusLost
        // TODO add your handling code here:
        if (txtApellido.getText().length()<2) {
            lblapellido.setForeground(Color.red);
        }else{
            lblapellido.setForeground(Color.green);
        }
    }//GEN-LAST:event_txtApellidoFocusLost

    private void txtTelefonoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelefonoFocusLost
        // TODO add your handling code here:
        if (txtTelefono.getText().length()<9) {
            lbltelefono.setForeground(Color.red);
        }else{
            lbltelefono.setForeground(Color.green);
        }
    }//GEN-LAST:event_txtTelefonoFocusLost

    private void txtDireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDireccionFocusLost
        // TODO add your handling code here:
        if (txtDireccion.getText().length()<4) {
            lbldireccion.setForeground(Color.red);
        }else{
            lbldireccion.setForeground(Color.green);
        }
    }//GEN-LAST:event_txtDireccionFocusLost

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        Conexion con=new Conexion();
        Connection accesoBD = con.getConexion();
        String ci,nombre,apellido,direccion,telefono,mail;
        ci=this.txtCedula.getText();
        nombre=this.txtNombre.getText();
        apellido=this.txtApellido.getText();
        direccion=this.txtDireccion.getText();
        telefono=this.txtTelefono.getText();
        mail=this.txtCorreo.getText();
        if(todoOK()){
            String query = "INSERT INTO persona (ci, nombre, apellido, direccion, telefono, correo) values (?, ?, ?, ?, ?, ?)";
            String query2 = "INSERT INTO cliente (ci) values (?)";
        PreparedStatement ingreso;
        PreparedStatement ingreso2;
        try {
            ingreso= accesoBD.prepareStatement(query);
            ingreso2=accesoBD.prepareStatement(query2);
            ingreso.setString(1, ci);
            ingreso.setString(2, nombre);
            ingreso.setString(3, apellido);
            ingreso.setString(4, direccion);
            ingreso.setString(5, telefono);
            ingreso.setString(6, mail);
            ingreso2.setString(1, ci);
            ingreso.executeUpdate();
            ingreso2.executeUpdate();
          JOptionPane.showMessageDialog(this, "Ingreso correcto");
          this.btnEliminar.setVisible(true);
          this.btnEliminar1.setVisible(true);
          this.btnAgregar.setVisible(false);
          txtCedula.setEditable(false);
          btnBuscar.setText("Otra Busqueda");
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } 
        }
        else{
            JOptionPane.showMessageDialog(this, "Se requiere todos los campos");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed
   
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        if(btnBuscar.getText().equals("Buscar")){
         
        String cedula = null;
        Conexion con=new Conexion();
        Connection accesoBD = con.getConexion();
              try{
          PreparedStatement consulta = accesoBD.prepareStatement("SELECT * FROM cliente WHERE ci = ?" );
         consulta.setString(1, this.txtCedula.getText());
         ResultSet resultado = consulta.executeQuery();
         while(resultado.next()){
             cedula=resultado.getString("ci");
             System.out.println("aqui:"+cedula);
         }
      }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "No se encontro");
      } 
              if(cedula==null){
                  JOptionPane.showMessageDialog(this, "No es encontro");
              }
              else{
               try {
                   PreparedStatement consulta2 = accesoBD.prepareStatement("SELECT nombre, apellido,direccion,telefono,correo FROM persona WHERE ci = ?" );
                   consulta2.setString(1, this.txtCedula.getText());
                    ResultSet resultado = consulta2.executeQuery();
                    while(resultado.next()){
                    this.txtNombre.setText(resultado.getString("nombre"));
                    this.txtApellido.setText(resultado.getString("apellido"));
                    this.txtDireccion.setText(resultado.getString("direccion"));
                    this.txtTelefono.setText(resultado.getString("telefono"));
                    this.txtCorreo.setText(resultado.getString("correo"));
                    this.btnBuscar.setText("Otra busqueda");
                    this.btnEliminar.setVisible(true);
                    this.btnEliminar1.setVisible(true);
                    this.btnAgregar.setVisible(false);
         }
               } catch (SQLException ex) {
                   Logger.getLogger(vistaClientes.class.getName()).log(Level.SEVERE, null, ex);
               }
        
              }
        }
        else{
            txtCedula.setText("");
            txtCedula.setEditable(true);
            txtNombre.setText("");
            txtNombre.setEditable(true);
            txtApellido.setText("");
            txtApellido.setEditable(true);
            txtDireccion.setText("");
            txtDireccion.setEditable(true);
            txtTelefono.setText("");
            txtTelefono.setEditable(true);
            txtCorreo.setText("");
            txtCorreo.setEditable(true);
            txtCedula.setEditable(true);
            btnEliminar.setVisible(false);
            btnEliminar1.setVisible(false);
            btnAgregar.setVisible(true);
            btnBuscar.setText("Buscar");
        }
          
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
          Conexion con=new Conexion();
        Connection accesoBD = con.getConexion();
            String ci=this.txtCedula.getText();
        try{
            PreparedStatement consulta2 = accesoBD.prepareStatement("DELETE FROM cliente WHERE ci = ?");
            consulta2.setString(1, ci);
            consulta2.executeUpdate();
            PreparedStatement consulta = accesoBD.prepareStatement("DELETE FROM persona WHERE ci = ?");
            consulta.setString(1, ci);
            consulta.executeUpdate();
            System.out.println(ci);
            JOptionPane.showMessageDialog(this, "Eliminacion exitosa");
            txtCedula.setText("");
            txtCedula.setEditable(true);
            txtNombre.setText("");
            txtNombre.setEditable(true);
            txtApellido.setText("");
            txtApellido.setEditable(true);
            txtDireccion.setText("");
            txtDireccion.setEditable(true);
            txtTelefono.setText("");
            txtTelefono.setEditable(true);
            txtCorreo.setText("");
            txtCorreo.setEditable(true);
            txtCedula.setEditable(true);
            btnEliminar.setVisible(false);
            btnEliminar1.setVisible(false);
            btnAgregar.setVisible(true);
            btnBuscar.setText("Buscar");
            
            //consulta2.executeUpdate();
            
      }catch(SQLException ex){
            System.out.println(ex);
      }
             
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        // TODO add your handling code here:
        Conexion con=new Conexion();
        Connection accesoBD = con.getConexion();
        if(this.txtCedula.getText().equals("")||this.txtNombre.getText().equals("")||this.txtApellido.getText().equals("")||this.txtDireccion.getText().equals("")||this.txtTelefono.getText().equals("")||this.txtCorreo.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Debe llenar todos los campos");
        }
        else{
            try {
            PreparedStatement pstm = accesoBD.prepareStatement("update persona set nombre= ?,apellido= ?, direccion= ? ,telefono= ?,correo=? where ci=?");
            pstm.setString(6, this.txtCedula.getText());
            pstm.setString(1, this.txtNombre.getText());
            pstm.setString(2, this.txtApellido.getText());
            pstm.setString(3, this.txtDireccion.getText());
            pstm.setString(4, this.txtTelefono.getText());
            pstm.setString(5, this.txtCorreo.getText());
            pstm.executeUpdate();
            JOptionPane.showMessageDialog(this, "Modificacion exitosa");
            txtCedula.setText("");
            txtCedula.setEditable(true);
            txtNombre.setText("");
            txtNombre.setEditable(true);
            txtApellido.setText("");
            txtApellido.setEditable(true);
            txtDireccion.setText("");
            txtDireccion.setEditable(true);
            txtTelefono.setText("");
            txtTelefono.setEditable(true);
            txtCorreo.setText("");
            txtCorreo.setEditable(true);
            txtCedula.setEditable(true);
            btnEliminar.setVisible(false);
            btnEliminar1.setVisible(false);
            btnAgregar.setVisible(true);
            btnBuscar.setText("Buscar");
        } catch (SQLException e) {
            System.out.println(e);
        }
        }
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    public boolean validaCedula(String x){
        int suma=0;
        if(x.length()==9){
            return false;
        }else{
            int a[]=new int [x.length()/2];
            int b[]=new int [(x.length()/2)];
            int c=0;
            int d=1;
            for (int i = 0; i < x.length()/2; i++) {
                a[i]=Integer.parseInt(String.valueOf(x.charAt(c)));
                c=c+2;
                if (i < (x.length()/2)-1) {
                    b[i]=Integer.parseInt(String.valueOf(x.charAt(d)));
                    d=d+2;
                }
            }
            for (int i = 0; i < a.length; i++) {
                a[i]=a[i]*2;
                if (a[i] >9){
                    a[i]=a[i]-9;
                }
                suma=suma+a[i]+b[i];
            } 
            int aux=suma/10;
            int dec=(aux+1)*10;
            if ((dec - suma) == Integer.parseInt(String.valueOf(x.charAt(x.length()-1))))
                return true;
            else
                if(suma%10==0 && x.charAt(x.length()-1)=='0'){
                    return true;
                }else{
                    return false;
                }
        }
    }
    public boolean todoOK(){
        if ("".equals(txtCedula.getText())) {
            lblci.setForeground(Color.red);
            return false;
        } else {
            if (!validaCedula(txtCedula.getText())) {
                lblci.setForeground(Color.red);
                return false;
            }
        }
        if (txtNombre.getText().length()<2) {
            lblnombre.setForeground(Color.red);
            return false;
        }
        if (txtApellido.getText().length()<2) {
            lblapellido.setForeground(Color.red);
            return false;
        }
        if (txtTelefono.getText().length()<9) {
            lbltelefono.setForeground(Color.red);
            return false;
        }
        if (txtDireccion.getText().length()<4) {
            lbldireccion.setForeground(Color.red);
            return false;
        }
        Pattern pat = null;
        Matcher mat = null;
        pat = Pattern.compile("^[\\w\\-\\_\\+]+(\\.[\\w\\-\\_]+)*@([A-Za-z0-9-]+\\.)+[A-Za-z]{2,4}$");
        mat = pat.matcher(txtCorreo.getText());
        if (mat.find()) {
        } else {
            lblcorreo.setForeground(Color.red);
            return false;
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaClientes(new EmpleadoVO()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnEliminar1;
    public javax.swing.JButton btnHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblapellido;
    private javax.swing.JLabel lblci;
    private javax.swing.JLabel lblcorreo;
    private javax.swing.JLabel lbldireccion;
    private javax.swing.JLabel lblnombre;
    private javax.swing.JLabel lbltelefono;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtCedula;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtDireccion;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
