/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.*;
import controlador.Validaciones;
/**
 *
 * @author DELL
 */
public class vistaPaquetes extends javax.swing.JFrame {
    PaquetesDAO pa=new PaquetesDAO();
    private EmpleadoVO user;        
    /**
     * Creates new form NewJFrame
     */
    public vistaPaquetes(EmpleadoVO user) {
        this.user=user;
        initComponents();
    this.combo.setModel(pa.ObtenerNombres());
    this.ComboServi.setModel(pa.ObtenerServicios());
     txtCostoPaquete.setText("0");
        txtCostoServicio.setText("0");
    btnMasServicio.setEnabled(false);
    btnMenosServicio.setEnabled(false); 
    ComboServi.setEnabled(false);
    btnTotal.setEnabled(false);
    btnGuardar.setEnabled(false);
       
    }

    /*
    *
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        labelServicio = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCostoPaquete = new javax.swing.JTextField();
        btnAnadir = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        txtCostoServicio = new javax.swing.JTextField();
        txtCostoTotal = new javax.swing.JTextField();
        labelPaquete = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaCompras = new javax.swing.JTable();
        btnTotal = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnMasServicio = new javax.swing.JButton();
        btnMenosServicio = new javax.swing.JButton();
        ComboServi = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Costo");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Servicio");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Incluye");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setLocation(new java.awt.Point(500, 180));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        getContentPane().add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoPequeño.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 720, 210));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Nombre Paquete");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        labelServicio.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        labelServicio.setText("==");
        getContentPane().add(labelServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 0, 10));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setText("Precio Total");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 700, 120, 40));

        txtCostoPaquete.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtCostoPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoPaqueteActionPerformed(evt);
            }
        });
        getContentPane().add(txtCostoPaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, -1, 20));

        btnAnadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        btnAnadir.setText("Seleccionar");
        btnAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnadirActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 160, -1));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/home.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 740, -1, -1));

        txtCostoServicio.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtCostoServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoServicioActionPerformed(evt);
            }
        });
        getContentPane().add(txtCostoServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, -1, -1));

        txtCostoTotal.setEditable(false);
        txtCostoTotal.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtCostoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoTotalActionPerformed(evt);
            }
        });
        getContentPane().add(txtCostoTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 700, 140, 30));

        labelPaquete.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        labelPaquete.setText(".");
        getContentPane().add(labelPaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, 310, 40));

        TablaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Precio", "Descripción"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TablaCompras);
        if (TablaCompras.getColumnModel().getColumnCount() > 0) {
            TablaCompras.getColumnModel().getColumn(1).setResizable(false);
            TablaCompras.getColumnModel().getColumn(1).setPreferredWidth(4);
            TablaCompras.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, 670, 120));

        btnTotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTotal.setText("Total");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });
        getContentPane().add(btnTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 700, -1, -1));

        btnGuardar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 740, -1, -1));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        btnNuevo.setText("Nuevo Paquete ");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 160, 50));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 160, 40));

        btnMasServicio.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnMasServicio.setText("+");
        btnMasServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasServicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnMasServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 60, 40));

        btnMenosServicio.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnMenosServicio.setText("-");
        btnMenosServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosServicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenosServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 70, 40));

        ComboServi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(ComboServi, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel8.setText("Servicio");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 750, 160));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 750, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCostoPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoPaqueteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoPaqueteActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        vistaMenuPrincipal vista = new vistaMenuPrincipal(user);
        vista.setVisible (true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnadirActionPerformed
   String nombre,servicios;
  labelPaquete.setText(combo.getSelectedItem().toString());
    // textArea.setText(ComboServi.getSelectedItem().toString());
    nombre=labelPaquete.getText();
  
    PaquetesDAO pa=new PaquetesDAO();
    PaqueteVO vo=new PaqueteVO();
    buscarNombreCombo(nombre);
      btnEliminar.setEnabled(false);
      btnNuevo.setEnabled(false);
      combo.setEnabled(false);
    
      btnMasServicio.setEnabled(true);
      btnMenosServicio.setEnabled(true);
      ComboServi.setEnabled(true);
      btnTotal.setEnabled(true);
//    float a=vo.getCosto();
//    txtCosto.setText(String.valueOf(a));
    }//GEN-LAST:event_btnAnadirActionPerformed

    private void txtCostoServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoServicioActionPerformed

    private void txtCostoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoTotalActionPerformed
float result=0;public void removeSelectedRows(JTable table){
   DefaultTableModel model = (DefaultTableModel) this.TablaCompras.getModel();
   int[] rows = table.getSelectedRows();
   for(int i=0;i<rows.length;i++){
     model.removeRow(rows[i]-i);
   }
}
    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
//   
  btnGuardar.setEnabled(true); 
        Totalizar();
      
      //  buscarNombreComboPrecioTotal();
    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       PaquetesDAO vo=new PaquetesDAO();
        vo.modificarPaqueteConServicios(labelPaquete.getText(), Float.parseFloat(txtCostoTotal.getText()));
        JOptionPane.showMessageDialog(null,"Paquete Actualizado Correctamente");
          vistaPaquetes vista = new vistaPaquetes(user);
        vista.setVisible (true);
        this.setVisible(false);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        Validaciones vali=new Validaciones();
        String respuesta = JOptionPane.showInputDialog("Escriba el nombre del nuevo Paquete");
           if(vali.validarCampodeNombre(respuesta)==true)
           {
               // JOptionPane.showMessageDialog(null, "nombre correcro", "Nombre valido", 1);
                PaquetesDAO pa=new PaquetesDAO();
               pa.AgregarNuevoPaquete(respuesta, 0);
                this.combo.setModel(pa.ObtenerNombres()); 
                
          }
           
           else
           {
              JOptionPane.showMessageDialog(null, "El Nombre ingresado es incorrecto", "Nombre no valido", 0);
                
           }
       
    }//GEN-LAST:event_btnNuevoActionPerformed
 private boolean esNombreValido(String nombre) {
    	if(nombre.matches("\\d+\\s+([a-zA-Z]+|[a-zA-Z]+\\s[a-zA-Z]+)"))
    		return false;
    	else
    		return true;
    }
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // String respuesta = JOptionPane.showInputDialog("Escriba el nombre del nuevo Paquete");
        PaquetesDAO pa=new PaquetesDAO();
        PaqueteServicioDAO ser=new PaqueteServicioDAO();

        ser.eliminarPaquete(combo.getSelectedItem().toString());
        pa.eliminarPaquete(combo.getSelectedItem().toString());
        System.out.println(combo.getSelectedItem().toString());

        this.combo.setModel(pa.ObtenerNombres());
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnMenosServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosServicioActionPerformed

        removeSelectedRows(TablaCompras);
        float costoPaque=0;
        float costoServi=0;
        PaquetesDAO vi=new PaquetesDAO();
        vi.eliminarServicio(ComboServi.getSelectedItem().toString());

        costoPaque=Float.parseFloat(txtCostoPaquete.getText());
        costoServi=Float.parseFloat(txtCostoServicio.getText());

        result=result-costoServi;
        txtCostoTotal.setText(Float.toString(result));
         txtCostoTotal.setText("");
    }//GEN-LAST:event_btnMenosServicioActionPerformed

    private void btnMasServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasServicioActionPerformed
        String servicios;
        labelServicio.setText(ComboServi.getSelectedItem().toString());
        servicios=labelServicio.getText();
        buscarServicioCombo(servicios);
        float costoPaque=0;
        float costoServi=0;

        costoPaque=Float.parseFloat(txtCostoPaquete.getText());
        costoServi=Float.parseFloat(txtCostoServicio.getText());

        result=result+(costoPaque+costoServi);
        // txtCostoTotal.setText(Float.toString(result));
        txtCostoPaquete.setText("0");
        txtCostoServicio.setText("0");
        PaquetesDAO paque=new PaquetesDAO();
        paque.AgregarServicioEnPquete(servicios, labelPaquete.getText());
           txtCostoTotal.setText("");
    }//GEN-LAST:event_btnMasServicioActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboActionPerformed

    int i=0;
    int total;
    public void buscarNombreCombo(String nombre) {
      int as;
        Conexion conex = new Conexion();
        Servicio_PaqueteVO BusPaque = new Servicio_PaqueteVO();
        PaqueteVO v=new PaqueteVO();
        boolean existe = false;
        try {
            //PreparedStatement consulta = conex.getConexion().prepareStatement("select *from servicio_paquete where nombre_pac='"+labelPaquete.getText()+"'");
            PreparedStatement consulta = conex.getConexion().prepareStatement("select nombre, costo from servicio_paquete, servicio\n" +
                "where nombre=nombre_ser\n" +
                "and nombre_pac='"+labelPaquete.getText()+"'");
           // consulta.setString(1, nombre);//
            ResultSet res = consulta.executeQuery();//permite que se ejecuta la busqueda en consulta, result set es un arraylist de los objetos de busqueda.
            while (res.next()) {
                existe = true;
                v.setNombre((res.getString("nombre")));
                v.setCosto((Float.parseFloat(res.getString("costo"))));
                // v.setCosto((Float.parseFloat(res.getString("costo"))));
                // persona.setId(res.getInt(1));
//                BusPaque.setCosto((Float.parseFloat(res.getString("costo"))));
                //String cos=Float.toString(v.getCosto());
               //  txtCostoPaquete.setText((cos));
      
         TablaCompras.setValueAt(v.getNombre(), i,0);
          TablaCompras.setValueAt(v.getCosto(), i,1);
        //TablaCompras.setValueAt(v.getNombre(), 1,1);
       //   TablaCompras.setValueAt(v.getCosto(), 0,0);
        //  TablaCompras.setValueAt(, 0,1);
        
          i++;
          //TablaCompras.setValueAt(BusPaque.getNombre_ser(), 0,1);
          existe = true;
              // buscarNombreComboPrecioTotal(labelPaquete.getText());
               // System.out.println(labelPaquete.getText());
            }
           total=i;
            res.close();
            conex.desconectar();

        } catch (SQLException e) {
            System.out.println("" + e.getMessage());
           
        }
        if (existe) {
//            
//         JOptionPane.showMessageDialog(null,"Paquete -->"+BusPaque.getNombre()+"  "+"Costo -->"+ BusPaque.getCosto());
     
        }
      }
    
   public void buscarNombreComboPrecioTotal() {

        Conexion conex = new Conexion();
        Servicio_PaqueteVO BusPaque = new Servicio_PaqueteVO();
        PaqueteVO vi=new PaqueteVO();
        boolean existe = false;
        try {
            //PreparedStatement consulta = conex.getConexion().prepareStatement("select *from servicio_paquete where nombre_pac='"+labelPaquete.getText()+"'");
            PreparedStatement consulta = conex.getConexion().prepareStatement("select *from paquete");
            consulta.setString(1, labelPaquete.getText());//
            ResultSet res = consulta.executeQuery();//permite que se ejecuta la busqueda en consulta, result set es un arraylist de los objetos de busqueda.
            while (res.next()) {
                existe = true;
                vi.setNombre((res.getString("nombre")));
                vi.setCosto((Float.parseFloat(res.getString("costo"))));
                //v.setCosto((Float.parseFloat(res.getString("costo"))));
                // persona.setId(res.getInt(1));
//                BusPaque.setCosto((Float.parseFloat(res.getString("costo"))));
                String cos=Float.toString(vi.getCosto());
                txtCostoTotal.setText((cos));
                  System.out.println(cos);
                  
         
        //TablaCompras.setValueAt(v.getNombre(), 1,1);
       //   TablaCompras.setValueAt(v.getCosto(), 0,0);
        //  TablaCompras.setValueAt(, 0,1);
        
          i++;
          //TablaCompras.setValueAt(BusPaque.getNombre_ser(), 0,1);
          existe = true;
             
            }
          
            res.close();
            conex.desconectar();

        } catch (SQLException e) {
            System.out.println("" + e.getMessage());
           
        }
        if (existe) {
//            
//         JOptionPane.showMessageDialog(null,"Paquete -->"+BusPaque.getNombre()+"  "+"Costo -->"+ BusPaque.getCosto());
     
        }
      }  
    
    
    
public int num(int n)
{
int a;
a=n;
return a;
}



int cont=1;

 public void buscarServicioCombo(String nombre) {
int totalServicio=total;      
        Conexion conex = new Conexion();
        ServicioVO BusServi = new ServicioVO();
        boolean existe = false;
        try {
            PreparedStatement consulta = conex.getConexion().prepareStatement("SELECT *FROM Servicio where nombre=?");
            consulta.setString(1, nombre);//
            ResultSet res = consulta.executeQuery();//permite que se ejecuta la busqueda en consulta, result set es un arraylist de los objetos de busqueda.
            while (res.next()) {
                existe = true;
                BusServi.setNombre((res.getString("nombre")));
                // persona.setId(res.getInt(1));
                BusServi.setCosto((Float.parseFloat(res.getString("costo"))));
                BusServi.setDescripcion(res.getString("descripcion"));
             existe = true;
             BusServi.setCosto((Float.parseFloat(res.getString("costo"))));
                 String cos=Float.toString(BusServi.getCosto());
                  txtCostoServicio.setText((cos));
                  
                  TablaCompras.setValueAt(BusServi.getNombre(), total,0);
                   TablaCompras.setValueAt(BusServi.getCosto(), total,1);
                    TablaCompras.setValueAt(BusServi.getDescripcion(), total,2);
            
                    cont++;
                    total++;
            }
            
            res.close();
            conex.desconectar();

        } catch (SQLException e) {
            System.out.println("" + e.getMessage());
           
        }
        if (existe) {
//         JOptionPane.showMessageDialog(null,"Servicio -->"+BusServi.getNombre()+"  "+"Costo -->"+ BusServi.getCosto()+"  "+"Descripcion -->"+BusServi.getDescripcion());
             
        } else {
             JOptionPane.showMessageDialog(null,"No se encontro el servicio");
        }
    }
                private void Totalizar(){
                    float sumatoria1=0;
        int totalRow= TablaCompras.getRowCount();
        totalRow-=1;
        for(int i=0;i<=(totalRow);i++)
        {
           float sumatoria= Float.parseFloat(String.valueOf(TablaCompras.getValueAt(i,1)));
//en la parte de arriba indica el primer parametro la fila y el segundo la columna la cual estaras //manejando
             sumatoria1+=sumatoria;
 txtCostoTotal.setText(String.valueOf(sumatoria1));
          System.out.println(""+sumatoria1);
         
 
           }
//                double t = 0;
//                double p = 0;
//                if(TablaCompras.getRowCount()>0){
//                for (int i = 1; i < TablaCompras.getRowCount(); i++) {
//                p = Double.parseDouble(TablaCompras.getValueAt(i, 1).toString());
//                t+=p;
//                }
//                aaa.setText("El total es: "+t);
//                }else{
//                //Sin Acciones
//                }
                }





      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaPaquetes(new EmpleadoVO()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboServi;
    public javax.swing.JTable TablaCompras;
    public javax.swing.JButton btnAnadir;
    public javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnHome;
    public javax.swing.JButton btnMasServicio;
    public javax.swing.JButton btnMenosServicio;
    public javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnTotal;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelPaquete;
    private javax.swing.JLabel labelServicio;
    public javax.swing.JTextField txtCostoPaquete;
    public javax.swing.JTextField txtCostoServicio;
    public javax.swing.JTextField txtCostoTotal;
    // End of variables declaration//GEN-END:variables
}
