/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import modelo.Conexion;
import modelo.EmpleadoVO;
import com.mxrck.autocompleter.TextAutoCompleter;
/**
 *
 * @author jhond
 */
public class vistaPromociones extends javax.swing.JFrame {
    private EmpleadoVO user;
    /**
     * Creates new form vistaEmpleados
     */
    public vistaPromociones(EmpleadoVO user) {
        this.user=user;
        initComponents();
        this.setLocationRelativeTo(null);
        this.btnEliminar.setVisible(false);
        this.btnEliminar1.setVisible(false);
        this.diaI.setText("0");
        this.mesI.setText("0");
        this.anioI.setText("0");
        this.DiaF.setText("0");
        this.mesF.setText("0");
        this.anioF.setText("0");
        Conexion con=new Conexion();
        Connection accesoBD = con.getConexion();
         TextAutoCompleter tac = new TextAutoCompleter(this.txtNombre);
        
       
         try{
         PreparedStatement consulta = accesoBD.prepareStatement("SELECT nombre FROM promocion" );
         
         ResultSet resultado = consulta.executeQuery();
         while(resultado.next()){
             tac.addItem(resultado.getString("nombre"));
         }
         
      }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "No se encontraron coincidencias");
      } 
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lblDescuento = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDescuento = new javax.swing.JTextField();
        anioI = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        lblanioi = new javax.swing.JLabel();
        lbldiai = new javax.swing.JLabel();
        diaI = new javax.swing.JTextField();
        lblmesi = new javax.swing.JLabel();
        mesI = new javax.swing.JTextField();
        lblaniof = new javax.swing.JLabel();
        lbldiaf = new javax.swing.JLabel();
        DiaF = new javax.swing.JTextField();
        anioF = new javax.swing.JTextField();
        lblmesf = new javax.swing.JLabel();
        mesF = new javax.swing.JTextField();
        btnHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoPequeño.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");

        lblnombre.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblnombre.setText("Nombre");

        lblDescuento.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblDescuento.setText("Descuento");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Inicio");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Fin");

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreFocusLost(evt);
            }
        });

        txtDescuento.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtDescuento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescuentoActionPerformed(evt);
            }
        });
        txtDescuento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescuentoFocusLost(evt);
            }
        });
        txtDescuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescuentoKeyTyped(evt);
            }
        });

        anioI.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        anioI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anioIActionPerformed(evt);
            }
        });
        anioI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                anioIFocusLost(evt);
            }
        });
        anioI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                anioIKeyTyped(evt);
            }
        });

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/añadir.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificar.png"))); // NOI18N
        btnEliminar1.setText("Modificar");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        lblanioi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblanioi.setText("Año");

        lbldiai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbldiai.setText("Día");

        diaI.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        diaI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                diaIFocusLost(evt);
            }
        });
        diaI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                diaIKeyTyped(evt);
            }
        });

        lblmesi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblmesi.setText("Mes");

        mesI.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        mesI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesIActionPerformed(evt);
            }
        });
        mesI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mesIFocusLost(evt);
            }
        });
        mesI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mesIKeyTyped(evt);
            }
        });

        lblaniof.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblaniof.setText("Año");

        lbldiaf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbldiaf.setText("Día");

        DiaF.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        DiaF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                DiaFFocusLost(evt);
            }
        });
        DiaF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DiaFKeyTyped(evt);
            }
        });

        anioF.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        anioF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anioFActionPerformed(evt);
            }
        });
        anioF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                anioFFocusLost(evt);
            }
        });
        anioF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                anioFKeyTyped(evt);
            }
        });

        lblmesf.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblmesf.setText("Mes");

        mesF.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        mesF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesFActionPerformed(evt);
            }
        });
        mesF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                mesFFocusLost(evt);
            }
        });
        mesF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mesFKeyTyped(evt);
            }
        });

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/home.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescuento)
                            .addComponent(lblnombre)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbldiaf)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(DiaF, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(15, 15, 15)
                                    .addComponent(lblmesf)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mesF, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblaniof)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(anioF, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbldiai)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(diaI, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(15, 15, 15)
                                    .addComponent(lblmesi)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(mesI, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lblanioi)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(anioI, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnHome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblnombre))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDescuento))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(diaI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbldiai))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(anioI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(mesI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblmesi)
                                .addComponent(lblanioi)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(DiaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lbldiaf))
                                    .addComponent(anioF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(mesF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblmesf)
                                        .addComponent(lblaniof)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(btnHome))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregar)
                        .addGap(4, 4, 4)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDescuentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescuentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescuentoActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        vistaMenuPrincipal vista = new vistaMenuPrincipal(user); 
        vista.setVisible (true);
        this.setVisible(false);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        Conexion con=new Conexion();
        Connection accesoBD = con.getConexion();
        String nombre,descuento,diaI,mesI,anioI,diaF,mesF,anioF;
        String fechaI,fechaF;
        nombre=this.txtNombre.getText();
        descuento=this.txtDescuento.getText();
        diaI=this.diaI.getText();
        mesI=this.mesI.getText();
        anioI=this.anioI.getText();
        diaF=this.DiaF.getText();
        mesF=this.mesF.getText();
        anioF=this.anioF.getText();
        fechaI=anioI+"/"+mesI+"/"+diaI;
        fechaF=anioF+"/"+mesF+"/"+diaF;
        if(validarCampos()){
              String query = "INSERT INTO promocion (nombre, descuento, fecha_inicio, fecha_fin) values (?, ?, ?, ?)";
        PreparedStatement ingreso;
        try {
            ingreso= accesoBD.prepareStatement(query);
            ingreso.setString(1, nombre);
            ingreso.setString(2, descuento);
            ingreso.setString(3, fechaI);
            ingreso.setString(4, fechaF);
            ingreso.executeUpdate();
          JOptionPane.showMessageDialog(this, "Ingreso correcto");
          
          
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        this.btnEliminar.setVisible(true);
          this.btnEliminar1.setVisible(true);
          this.btnAgregar.setVisible(false);
        this.btnBuscar.setText("Otra busqueda");
        }
        if(this.diaI.equals("")){
            JOptionPane.showMessageDialog(this, "No se pudo agregar");
        }    
    }//GEN-LAST:event_btnAgregarActionPerformed
    
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        Conexion con=new Conexion();
        int bandera=0;
        Connection accesoBD = con.getConexion();
       
        if(btnBuscar.getText()==("Buscar")){
        try{
         PreparedStatement consulta = accesoBD.prepareStatement("SELECT descuento, fecha_inicio,fecha_fin FROM promocion WHERE nombre = ?" );
         consulta.setString(1, this.txtNombre.getText());
         ResultSet resultado = consulta.executeQuery();
         while(resultado.next()){
             //this.txtNombre.setText(resultado.getString("nombre"));
             this.txtDescuento.setText(resultado.getString("descuento"));
             String pal=resultado.getDate("fecha_inicio").toString();
             String pal2=resultado.getDate("fecha_fin").toString();
             String[] parts = pal.split("-");
             String anio = parts[0];
             String mes = parts[1]; 
             String dia = parts[2];
             String[] parts2 = pal2.split("-");
             String anio2 = parts2[0];
             String mes2 = parts2[1]; 
             String dia2 = parts2[2];
             this.diaI.setText(dia);
             this.mesI.setText(mes);
             this.anioI.setText(anio);
             this.DiaF.setText(dia2);
             this.mesF.setText(mes2);
             this.anioF.setText(anio2);
             this.btnBuscar.setText("Otra Busqueda");
             this.btnEliminar.setVisible(true);
             this.btnEliminar1.setVisible(true);
             this.btnAgregar.setVisible(false);
             bandera=1;
         }
         
      }catch(SQLException ex){
            JOptionPane.showMessageDialog(this, "No se encontraron coincidencias");
      } 
        if(bandera==0){
           JOptionPane.showMessageDialog(this, "No se encontraron coincidencias"); 
        }
        }
        else{
           this.txtNombre.setText("");
           this.txtDescuento.setText("");
           this.diaI.setText("");
           this.mesI.setText("");
           this.anioI.setText("");
           this.DiaF.setText("");
           this.mesF.setText("");
           this.anioF.setText("");
           this.btnAgregar.setVisible(true);
           this.btnEliminar1.setVisible(false);
           this.btnEliminar.setVisible(false);
            lblnombre.setForeground(Color.black);
            lblDescuento.setForeground(Color.black);
            lbldiai.setForeground(Color.black);
            lblmesi.setForeground(Color.black);
            lblanioi.setForeground(Color.black);
            lbldiaf.setForeground(Color.black);
            lblmesf.setForeground(Color.black);
            lblaniof.setForeground(Color.black);
            btnBuscar.setText("Buscar");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        Conexion con=new Conexion();
        int bandera=0;
        Connection accesoBD = con.getConexion();
            String nombre=this.txtNombre.getText();
        try{
         PreparedStatement consulta = accesoBD.prepareStatement("DELETE FROM promocion WHERE nombre = ?");
         consulta.setString(1, nombre);
         JOptionPane.showMessageDialog(this, "Eliminacion exitosa");
         this.txtNombre.setText("");
           this.txtDescuento.setText("");
           this.diaI.setText("");
           this.mesI.setText("");
           this.anioI.setText("");
           this.DiaF.setText("");
           this.mesF.setText("");
           this.anioF.setText("");
           this.btnAgregar.setVisible(true);
           this.btnEliminar1.setVisible(false);
           this.btnEliminar.setVisible(false);
            lblnombre.setForeground(Color.black);
            lblDescuento.setForeground(Color.black);
            lbldiai.setForeground(Color.black);
            lblmesi.setForeground(Color.black);
            lblanioi.setForeground(Color.black);
            lbldiaf.setForeground(Color.black);
            lblmesf.setForeground(Color.black);
            lblaniof.setForeground(Color.black);
            btnBuscar.setText("Buscar");
         consulta.executeUpdate();
      }catch(SQLException ex){  
            JOptionPane.showMessageDialog(this, "No se encontro");
      }
        
            
    }//GEN-LAST:event_btnEliminarActionPerformed
    
    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        // TODO add your handling code here:
         Conexion con=new Conexion();
        Connection accesoBD = con.getConexion();
        
        
            try {
            PreparedStatement pstm = accesoBD.prepareStatement("update promocion set descuento= ? where nombre=?");
            pstm.setString(2, this.txtNombre.getText());
            pstm.setString(1, this.txtDescuento.getText());
            pstm.executeUpdate();
            JOptionPane.showMessageDialog(this, "Modificacion exitosa");
            this.txtNombre.setText("");
           this.txtDescuento.setText("");
           this.diaI.setText("");
           this.mesI.setText("");
           this.anioI.setText("");
           this.DiaF.setText("");
           this.mesF.setText("");
           this.anioF.setText("");
           this.btnAgregar.setVisible(true);
           this.btnEliminar1.setVisible(false);
           this.btnEliminar.setVisible(false);
            lblnombre.setForeground(Color.black);
            lblDescuento.setForeground(Color.black);
            lbldiai.setForeground(Color.black);
            lblmesi.setForeground(Color.black);
            lblanioi.setForeground(Color.black);
            lbldiaf.setForeground(Color.black);
            lblmesf.setForeground(Color.black);
            lblaniof.setForeground(Color.black);
            btnBuscar.setText("Buscar");
        } catch (SQLException e) {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtDescuentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescuentoKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if ((int)validar>32 && (int)validar<=47
                || (int)validar>58 && (int)validar<=255) {
            getToolkit().beep();
            evt.consume();
        }
        if (this.txtDescuento.getText().length()>=2) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtDescuentoKeyTyped

    private void diaIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diaIKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if ((int)validar>32 && (int)validar<=47
                || (int)validar>58 && (int)validar<=255) {
            getToolkit().beep();
            evt.consume();
        }
        if (this.diaI.getText().length()>=2) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_diaIKeyTyped

    private void mesIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mesIKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if ((int)validar>32 && (int)validar<=47
                || (int)validar>58 && (int)validar<=255) {
            getToolkit().beep();
            evt.consume();
        }
        if (this.mesI.getText().length()>=2) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_mesIKeyTyped

    private void anioIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anioIActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_anioIActionPerformed

    private void anioIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anioIKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if ((int)validar>32 && (int)validar<=47
                || (int)validar>58 && (int)validar<=255) {
            getToolkit().beep();
            evt.consume();
        }
        if (this.anioI.getText().length()>=4) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_anioIKeyTyped

    private void DiaFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DiaFKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if ((int)validar>32 && (int)validar<=47
                || (int)validar>58 && (int)validar<=255) {
            getToolkit().beep();
            evt.consume();
        }
        if (this.DiaF.getText().length()>=2) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_DiaFKeyTyped

    private void mesFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mesFKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if ((int)validar>32 && (int)validar<=47
                || (int)validar>58 && (int)validar<=255) {
            getToolkit().beep();
            evt.consume();
        }
        if (mesF.getText().length()>=2) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_mesFKeyTyped

    private void anioFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anioFActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_anioFActionPerformed

    private void anioFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anioFKeyTyped
        // TODO add your handling code here:
        char validar=evt.getKeyChar();
        if ((int)validar>32 && (int)validar<=47
                || (int)validar>58 && (int)validar<=255) {
            getToolkit().beep();
            evt.consume();
        }
        if (anioF.getText().length()>=4) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_anioFKeyTyped

    private void txtDescuentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescuentoFocusLost
        // TODO add your handling code here:
        if(Integer.parseInt(txtDescuento.getText())>100||this.txtDescuento.getText().equals("")){
            lblDescuento.setForeground(Color.red);
        }
        else{
            lblDescuento.setForeground(Color.green);
        }
    }//GEN-LAST:event_txtDescuentoFocusLost

    private void mesIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesIActionPerformed

    private void mesFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesFActionPerformed

    private void diaIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_diaIFocusLost
        // TODO add your handling code here:
        
        if(Integer.parseInt(this.diaI.getText())>31||this.diaI.getText().equals("")){
           lbldiai.setForeground(Color.red); 
        }
        else{
            lbldiai.setForeground(Color.green);
        }
       
    }//GEN-LAST:event_diaIFocusLost

    private void mesIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mesIFocusLost
        // TODO add your handling code here:
         if(Integer.parseInt(this.mesI.getText())>12||this.mesI.getText().equals("")){
           lblmesi.setForeground(Color.red); 
        }
        else{
            lblmesi.setForeground(Color.green);
        }
    }//GEN-LAST:event_mesIFocusLost

    private void anioIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_anioIFocusLost
        // TODO add your handling code here:
         if(Integer.parseInt(this.anioI.getText())<2019||this.anioI.getText().equals("")){
           lblanioi.setForeground(Color.red); 
        }
        else{
            lblanioi.setForeground(Color.green);
        }
    }//GEN-LAST:event_anioIFocusLost

    private void DiaFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DiaFFocusLost
        // TODO add your handling code here:
         if(Integer.parseInt(this.DiaF.getText())>31||this.DiaF.getText().equals("")){
           lbldiaf.setForeground(Color.red); 
        }
        else{
            lbldiaf.setForeground(Color.green);
        }
    }//GEN-LAST:event_DiaFFocusLost

    private void mesFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mesFFocusLost
        // TODO add your handling code here:
         if(Integer.parseInt(this.mesF.getText())>12||this.mesF.getText().equals("")){
           lblmesf.setForeground(Color.red); 
        }
        else{
            lblmesf.setForeground(Color.green);
        }
    }//GEN-LAST:event_mesFFocusLost

    private void anioFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_anioFFocusLost
        // TODO add your handling code here:
         if(Integer.parseInt(this.anioF.getText())<2019||this.anioF.getText().equals("")){
           lblaniof.setForeground(Color.red); 
        }
        else{
            lblaniof.setForeground(Color.green);
        }
    }//GEN-LAST:event_anioFFocusLost

    private void txtNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreFocusLost
        // TODO add your handling code here:
        if(txtNombre.getText().equals("")){
           lblnombre.setForeground(Color.red); 
        }
        else{
            lblnombre.setForeground(Color.green);
        }
    }//GEN-LAST:event_txtNombreFocusLost

    boolean validarCampos(){
        
        if(this.txtDescuento.getText().equals("")||Integer.parseInt(this.txtDescuento.getText())>100){
            this.lblDescuento.setForeground(Color.red);
            JOptionPane.showMessageDialog(this, "Verificar el campo descuento");
            return false;
        }
        if(this.txtNombre.getText().equals("")){
            this.lblnombre.setForeground(Color.red);
            JOptionPane.showMessageDialog(this, "Se requiere rellenar el campo nombre");
            return false;
        }
        if(Integer.parseInt(this.diaI.getText())>31||this.diaI.getText().equals("0")){
            this.lbldiai.setForeground(Color.red);
            JOptionPane.showMessageDialog(this, "Revisar el dia de inicio");
            return false;
        }
        if(Integer.parseInt(this.mesI.getText())>12||this.mesI.getText().equals("0")){
            this.lblmesi.setForeground(Color.red);
            JOptionPane.showMessageDialog(this, "Revisar el mes de inicio");
            return false;
        }
        if(Integer.parseInt(this.anioI.getText())<2019||this.anioI.getText().equals("0")){
            this.lbldiai.setForeground(Color.red);
            JOptionPane.showMessageDialog(this, "Revisar el año de inicio");
            return false;
        }
        if(Integer.parseInt(this.DiaF.getText())>31||this.DiaF.getText().equals("0")){
            this.lbldiaf.setForeground(Color.red);
            JOptionPane.showMessageDialog(this, "Revisar el dia de finalizacion");
            return false;
        }
        if(Integer.parseInt(this.mesF.getText())>12||this.mesF.getText().equals("0")){
            this.lblmesf.setForeground(Color.red);
            JOptionPane.showMessageDialog(this, "Revisar el mes de finalizacion");
            return false;
        }
        if(Integer.parseInt(this.anioF.getText())<2019||this.anioF.getText().equals("0")){
            this.lblaniof.setForeground(Color.red);
            JOptionPane.showMessageDialog(this, "Revisar el año de finalizacion");
            return false;
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaPromociones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaPromociones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaPromociones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaPromociones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaPromociones(new EmpleadoVO()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField DiaF;
    public javax.swing.JTextField anioF;
    public javax.swing.JTextField anioI;
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnEliminar1;
    public javax.swing.JButton btnHome;
    public javax.swing.JTextField diaI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblDescuento;
    private javax.swing.JLabel lblaniof;
    private javax.swing.JLabel lblanioi;
    private javax.swing.JLabel lbldiaf;
    private javax.swing.JLabel lbldiai;
    private javax.swing.JLabel lblmesf;
    private javax.swing.JLabel lblmesi;
    private javax.swing.JLabel lblnombre;
    public javax.swing.JTextField mesF;
    public javax.swing.JTextField mesI;
    public javax.swing.JTextField txtDescuento;
    public javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
